export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  originalPrice?: number;
  billingCycle: string;
  rating: number;
  downloads: string;
  image: string;
  category: string;
}

export const products: Product[] = [
  {
    id: "chatgpt-plus",
    name: "ChatGPT Plus",
    description: "Tài khoản ChatGPT Plus chính chủ, sử dụng model GPT-4 và các tính năng nâng cao mới nhất.",
    price: 200000,
    originalPrice: 530000,
    billingCycle: "tháng",
    rating: 4.9,
    downloads: "10k+",
    image: "https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg",
    category: "AI",
  },
  {
    id: "chatgpt-go",
    name: "ChatGPT GO",
    description: "Gói ChatGPT GO tiết kiệm, sử dụng 12 tháng với mức giá siêu ưu đãi.",
    price: 450000,
    originalPrice: 2550000,
    billingCycle: "12 tháng",
    rating: 4.8,
    downloads: "5k+",
    image: "https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg",
    category: "AI",
  },
  {
    id: "gemini-pro",
    name: "Gemini AI Pro",
    description: "Google Gemini Pro mang đến sức mạnh AI tuyệt đỉnh được tích hợp sâu vào hệ sinh thái Google.",
    price: 249000,
    originalPrice: 5868000,
    billingCycle: "năm",
    rating: 4.8,
    downloads: "8k+",
    image: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Google_Gemini_logo.svg",
    category: "AI",
  },
  {
    id: "office-365-personal",
    name: "Office 365 Cá nhân",
    description: "Bản quyền Office 365 chính hãng dành cho 1 người dùng, đi kèm 1TB OneDrive.",
    price: 249000,
    originalPrice: 2500000,
    billingCycle: "năm",
    rating: 5.0,
    downloads: "20k+",
    image: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Microsoft_Office_logo_%282019%E2%80%93present%29.svg",
    category: "Office",
  },
  {
    id: "office-365-family",
    name: "Office 365 Family",
    description: "Bản quyền Office 365 gia đình cho 6 người dùng, mỗi người 1TB lưu trữ.",
    price: 599000,
    originalPrice: 3100000,
    billingCycle: "năm",
    rating: 4.9,
    downloads: "15k+",
    image: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Microsoft_Office_logo_%282019%E2%80%93present%29.svg",
    category: "Office",
  },
  {
    id: "win-11-pro",
    name: "KEY WIN 11 PRO",
    description: "Key cấp phép Windows 11 Pro trọn đời chính hãng, update tự do.",
    price: 199000,
    billingCycle: "vĩnh viễn",
    rating: 4.9,
    downloads: "50k+",
    image: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Windows_11_logo.svg",
    category: "OS",
  },
  {
    id: "grok-super",
    name: "GROK super",
    description: "AI Grok không giới hạn với dữ liệu cập nhật theo thời gian thực từ mạng xã hội X.",
    price: 349000,
    originalPrice: 790000,
    billingCycle: "tháng",
    rating: 4.7,
    downloads: "2k+",
    image: "https://upload.wikimedia.org/wikipedia/commons/c/ce/X_logo_2023.svg",
    category: "AI",
  },
  {
    id: "canva-pro",
    name: "Canva Pro",
    description: "Thiết kế mọi thứ với Canva Pro, mở khóa toàn bộ template, element và font chữ premium.",
    price: 179000,
    originalPrice: 1800000,
    billingCycle: "năm",
    rating: 5.0,
    downloads: "100k+",
    image: "https://upload.wikimedia.org/wikipedia/en/3/3b/Canva_Logo.png",
    category: "Design",
  },
  {
    id: "capcut-pro",
    name: "Capcut Pro",
    description: "Phần mềm chỉnh sửa video top 1, mở khóa toàn bộ hiệu ứng chuyển cảnh, bộ lọc.",
    price: 69000,
    originalPrice: 1800000,
    billingCycle: "năm",
    rating: 4.8,
    downloads: "30k+",
    image: "https://upload.wikimedia.org/wikipedia/en/2/21/CapCut_logo.svg",
    category: "Video",
  },
  {
    id: "combo-cham-chi",
    name: "Combo Chăm Chỉ",
    description: "Bao gồm Goodnotes 6 & CollaNote. Hỗ trợ đắc lực cho việc ghi chú.",
    price: 179000,
    billingCycle: "vĩnh viễn",
    rating: 4.9,
    downloads: "12k+",
    image: "",
    category: "Combo iOS",
  },
  {
    id: "combo-cam-ky",
    name: "Combo Cầm Kỳ Thi Họa",
    description: "Goodnotes 6 + Procreate + CollaNote. Vẽ và ghi chú đỉnh cao.",
    price: 249000,
    billingCycle: "vĩnh viễn",
    rating: 5.0,
    downloads: "8k+",
    image: "",
    category: "Combo iOS",
  },
];
